baseURL = "https://sumercip.com"
languageCode = "en-us"
title = "Welcome! | Sümer Cip"
theme = "my_yinyang"
DefaultContentLanguage = "en"
pygmentsUseClasses = true
pygmentsCodefences = true

[markup]
  [markup.goldmark.renderer]
    unsafe = true

[markup.highlight]
  guessSyntax = true
  tabWidth = 2

[params]
mainSections = ["posts"]
description = "My notes on random stuff about tech"
favicon = "/images/favico.svg"

[params.author]
name = "Sümer Cip"
homepage = "https://sumercip.com/"


[[params.socials]]
name = "Home"
link = "/"

[[params.socials]]
name = "Articles"
link = "/articles"

[[params.socials]]
name = "Talks"
link = "/talks"

[[params.socials]]
name = "About"
link = "/about"
